[package]
authors = ["Juliano Dorigão <https://github.com/jdorigao>"]
categories = ["command-line-utilities"]
description = "Manages screen resolution and display settings"
license = "MIT"
name = "regmsg"
version = "0.0.1"
edition = "2024"

[dependencies]
log = "0.4.27"
simplelog = "0.12.2"
clap = "4.5.35"
drm = "0.14.1"
swayipc = "3.0.3"
chrono = "0.4.40"

[profile.release]
lto = true          # Enable LTO.
strip = true        # Automatically strip symbols from the binary.
codegen-units = 1   # Use a single codegen for size optimization.
panic = "abort"     # Remove traceback information.
