[package]
authors = ["Juliano Dorigão <https://github.com/jdorigao>"]
categories = ["command-line-utilities"]
description = "Manages screen resolution and display settings"
license = "MIT"
name = "regmsg"
version = "0.0.0"
edition = "2024"
rust-version = "1.85.1"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
drm = "0.14.1"
swayipc = "3.0.3"
chrono = "0.4.40"
